title: Aditya Jeevannavar
subtitle: Bioinformatician. Absurdist writer. Tech dilettante.
description: >- # this means to ignore newlines until "baseurl:"
  I conduct bioinformatics research as my dayjob and continue to stare at my laptop screen writing and tinkering on side-projects the rest of the day.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Curriculum Vitae
      url: /cv
    - text: Impossible List
      url : /impossible/

# Edit Author details

author_logo: profile.png
author: Aditya Jeevannavar
author_bio: I work in bioinformatics by trade and in writing by hobby.
author_email: "aditya@jeevannavar.com"
author_location: India
author_website_url: "https://www.jeevannavar.com"
typewrite-text: I conduct bioinformatics research as my dayjob and continue to stare at my laptop screen writing and tinkering on side-projects the rest of the day.

# Experiences
author_work_experiences:
            - company_name: Initiative for Biological Systems Engineering, IIT Madras
              company_logo: ibse.png
              company_url: https://ibse.iitm.ac.in/
              designation: Student Researcher
              description: 
                - Integrating multi-omics data using Graph Convolutional Networks and View Correlation Discovery Network
                - Utilizing pairwise interactions to iimprove performance and interpretability of hte graph convolution based model
                - Processing multi-omics and multi-tissue data
              visibility: true
            - company_name: Indian Institute of Technology Madras
              company_logo: iitm.png
              company_url: https://www.iitm.ac.in
              designation: Teaching Assistant
              description: 
                - Conducted introductory molecular biology classes and tutorials for a class of 20 students
                - Assembled resources repositories for course projects on Moodle
                - Created and graded assignments using Overleaf and Gradescope respectively
              visibility: true
            - company_name: Molecular Plant Biology Unit, University of Turku
              company_logo: utu.jpg
              company_url: https://www.utu.fi
              designation: Laboratory Assistant
              description: 
                - Prepared various sterile glassware, media, broths, and stocks for microbial cultures and assays
                - Maintained photosynthetic microbial cultures, measured growth, and imaged them under a compund microscope
                - Ligated, inserted, and isolated plasmids, and performed gel electrophoreses
              visibility: true
            - company_name: Centre for BioSystems Science andn Engineering, Indian Institute of science
              company_logo: bsse.jpg
              company_url: https://be.iisc.ac.in/BEST.html
              designation: Bio Engineering summer Training Program Interm
              description: 
                - Created new S. pombe strains for study using random spore analysis and replica plating
                - Used fluorescent markers and confocal microscopy to visualize yeast mitochondrial proteins and nuclei
                - Analysed the microscopy data using FIJI and MATLAB
              visibility: true
            - company_name: Department of Biotechnology, IIT Madras
              company_logo: igem.png
              company_url: https://2017.igem.org/Team:IIT-Madras
              designation: iGEM Team Member
              description: 
               - Started The Language Project, a bio-science communication project in Indian and foreign languages
               - Worked on ChassiDex, a unique resource for easy access and sharing of scientific protocols
               - Maintained cultures, ran growth assays, prepared ultra-competent cells, and performed cell transformation
              visibility: true

# Education
author_education_details:
              - college_logo: iitm.png
                college_name: Indian Institute of Technology Madras
                college_url: https://www.iitm.ac.in
                college_degree: BS-MS (Dual Degree) in Biological Sciences
                description: 
                visibility: true
              - college_logo: utu.jpg
                college_name: University of Turku
                college_url: https://www.utu.fi
                college_degree: Student Exchange Program
                description: 
                visibility: true
                

# show_author_extracurriculars
author_extracurriculars_details:
              - logo: t5e.jpg
                title: Writer and Editor
                org: The Fifth Estate (T5E)
                description: Wrote and edited articles for T5E, IIT Madras' student media body
                url: https://t5eiitm.org
                visibility: true
                
              - logo: iitmtv.png
                title: Scriptwriter
                org: IITMTV & Pod,da
                description: Wrote stories and scripts for short films, musicals, and podcasts
                url: https://www.youtube.com/user/IITMTV
                visibility: true
            
              - logo: t5epodcast.png
                title: Consultant
                org: Vox Populi Vox Insti, the T5E Podcast
                description: Consulted and created content for the podcast
                url: https://t5epod.in
                visibility: true
                
# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true

# social links
twitter_username: eggsywastaken
github_username:  jeevannavar
facebook_username: aditya.jeevannavar
linkedin_username: AdiJ

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: 

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://username.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
#formspree_email: aditya.jeevan@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: none

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false
show_author_extracurriculars: true

# pagination of posts
paginate: 10
per_page: 10
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
